export const SET_SEARCH_KEY = 'SET_SEARCH_KEY';
export const SET_ROBOTS_PENDING = 'SET_ROBOTS_PENDING';
export const SET_ROBOTS_SUCCESS = 'SET_ROBOTS_SUCCESS';
export const SET_ROBOTS_FAILED = 'SET_ROBOTS_FAILED';
